-- PRODUCT: 판매중인 상품들의 상품 정보
-- OFFLINE_SALE: 오프라인 상품 판매 정보
SELECT PRODUCT_CODE, SUM(p.PRICE * o.SALES_AMOUNT) as SALES
FROM PRODUCT as p, OFFLINE_SALE as o
WHERE p.PRODUCT_ID = o.PRODUCT_ID  
GROUP BY o.PRODUCT_ID
ORDER BY SALES DESC, p.PRODUCT_CODE ASC