-- FISH_INFO: 잡은 물고기들의 정보
-- 잡은 물고기의 길이가 10cm 이하일 경우에는 LENGTH 가 NULL 
-- FISH_NAME_INFO: 물고기의 이름에 대한 정보

SELECT COUNT(*) AS FISH_COUNT, FISH_NAME
FROM FISH_NAME_INFO N, FISH_INFO I
WHERE N.FISH_TYPE = I.FISH_TYPE
GROUP BY I.FISH_TYPE
ORDER BY FISH_COUNT DESC