-- HR_DEPARTMENT 테이블은 회사의 부서 정보
-- HR_EMPLOYEES 테이블은 회사의 사원 정보
-- HR_GRADE 테이블은 2022년 사원의 평가 정보

SELECT SUM(SCORE) AS SCORE, G.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
FROM HR_EMPLOYEES E, HR_GRADE G
WHERE E.EMP_NO = G.EMP_NO
GROUP BY YEAR, EMP_NO
HAVING G.YEAR = '2022'
ORDER BY 1 DESC
LIMIT 1;