-- 상반기 주문 정보를 담은 FIRST_HALF
-- 아이스크림 성분에 대한 정보를 담은 ICECREAM_INFO
SELECT i.INGREDIENT_TYPE, sum(f.TOTAL_ORDER) as TOTAL_ORDER
FROM FIRST_HALF as f, ICECREAM_INFO as i
WHERE f.FLAVOR = i.FLAVOR
GROUP BY i.INGREDIENT_TYPE
ORDER BY f.TOTAL_ORDER ASC